version: "3"
services:
  eureka-server:
    environment:
      CONFIG_LOGIN_PWD: 12345
    image: itmabo/eureka-server
    volumes:
      - /home/log:/home/log
    prots:
      - 8761:8761
#    networks:
#      - tonynet-a
    deploy:
      placement:
        constraints: [node.role==manager]
  portainer:
    image: portainer/portainer
    ports:
      - 9999:9000
    volumes:
      - /home/portainer/data:/data
    #networks:
    #  - tonynet-a
    deploy:
      placement:
        constraints: [node.role==manager]
  rabbitmq-server: #单机版
    image: rabbitmq:management
    hostname: rabbitmq-server
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
#networks:
#  tonynet-a:
#    external:
#      name: tonynet