version: "3"
services:
  eureka-server:
    environment:
      CONFIG_LOGIN_PWD: 12345
    image: itmabo/eureka-server
    volumes:
      - /home/log:/home/log
    ports:
      - 8761:8761
#    networks:
#      - tonynet-a
    deploy:
      placement:
        constraints: [node.role==manager]
#networks:
#  tonynet-a:
#    external:
#      name: tonynet